image: debian:buster

stages:
  - test

variables:
  DB_PASSWORD: dbcuttest
  DB_NAME: dbcuttest
  DB_USER: dbcuttest
  POSTGRES_DB: $DB_NAME
  POSTGRES_USER: $DB_USER
  POSTGRES_PASSWORD: $DB_PASSWORD
  MYSQL_DATABASE: $DB_NAME
  MYSQL_ROOT_PASSWORD: $DB_PASSWORD


services:
- name: mariadb:latest
  alias: mariadb-1
- name: mariadb:latest
  alias: mariadb-2
- name: postgres:latest
  alias: postgres


test:
  stage: test
  script:
    - apt-get install -y default-libmysqlclient-dev libpq-dev make python3-pip
    - make init
    - make test
