image: debian:buster

stages:
  - test

variables:
  DB_PASSWORD: dbcuttest
  DB_NAME: dbcuttest
  DB_USER: dbcuttest
  MYSQL_DATABASE_WITH_DATA: mariadb-1
  MYSQL_DATABASE_WITHOUT_DATA: mariadb-2
  POSTGRES_DATABASE_WITHOUT_DATA: postgres
  POSTGRES_DB: $DB_NAME
  POSTGRES_USER: $DB_USER
  POSTGRES_PASSWORD: $DB_PASSWORD
  MYSQL_DATABASE: $DB_NAME
  MYSQL_ROOT_PASSWORD: $DB_PASSWORD


services:
- name: mariadb:latest
  alias: mariadb-1
- name: mariadb:latest
  alias: mariadb-2
- name: postgres:latest


test:
  stage: test
  script:
    - apt-get update
    - apt-get install -y default-libmysqlclient-dev libpq-dev make python3-pip mariadb-client
    - echo "GRANT ALL ON *.* to '$DB_USER'@'%' IDENTIFIED BY '$DB_PASSWORD';" | mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mariadb-1 "$MYSQL_DATABASE"
    - echo "GRANT ALL ON *.* to '$DB_USER'@'%' IDENTIFIED BY '$DB_PASSWORD';" | mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mariadb-2 "$MYSQL_DATABASE"
    - cat docker/testmysql_with_data/dump.sql | mysql --user=$DB_USER --password="$DB_PASSWORD" --host=mariadb-1 "$MYSQL_DATABASE"
    - make init
    - make test
