stages:
  - test

.test_suite: &test_suite
  image: git.itsf.io:5005/docker/dind-compose
  stage: test
  tags:
    - dind
  script:
    - make docker-test


python36_mariadb103_postgres95:
  <<: *test_suite
  variables:
    PYTHON_IMAGE: python:3.6
    MYSQL_IMAGE: mariadb:10.3
    POSTGRES_IMAGE: postgres:9.5

python36_mariadb103_postgres11:
  <<: *test_suite
  variables:
    PYTHON_IMAGE: python:3.6
    MYSQL_IMAGE: mariadb:10.3
    POSTGRES_IMAGE: postgres:11

python37_mariadb103_postgres95:
  <<: *test_suite
  variables:
    PYTHON_IMAGE: python:3.7
    MYSQL_IMAGE: mariadb:10.3
    POSTGRES_IMAGE: postgres:9.5

python37_mariadb103_postgres11:
  <<: *test_suite
  variables:
    PYTHON_IMAGE: python:3.7
    MYSQL_IMAGE: mariadb:10.3
    POSTGRES_IMAGE: postgres:11

python38_mariadb103_postgres95:
  <<: *test_suite
  variables:
    PYTHON_IMAGE: python:3.8
    MYSQL_IMAGE: mariadb:10.3
    POSTGRES_IMAGE: postgres:9.5

python38_mariadb103_postgres11:
  <<: *test_suite
  variables:
    PYTHON_IMAGE: python:3.8
    MYSQL_IMAGE: mariadb:10.3
    POSTGRES_IMAGE: postgres:11


before_script:
  - make docker-build

script:
  - make docker-test

after_script:
  - make docker-cleanup