image:
  name: docker/compose:1.23.2
  entrypoint: [""]

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DB_PASSWORD: dbcuttest
  DB_NAME: dbcuttest
  DB_USER: dbcuttest

services:
  - docker:dind

before_script:
  - docker version
  - docker-compose version

stages:
  - build
  - test

build:
  stage: build
  script:
    - docker-compose build

test:
  stage: test
  script:
    - docker-compose run --rm dbcut_app
