image: python:3.6

stages:
  - build
  - test

variables:
  DB_PASSWORD: dbcuttest
  DB_NAME: dbcuttest
  DB_USER: dbcuttest
  POSTGRES_DB: $DB_NAME
  POSTGRES_USER: $DB_USER
  POSTGRES_PASSWORD: $DB_PASSWORD
  MYSQL_DATABASE: $DB_NAME
  MYSQL_ROOT_PASSWORD: $DB_PASSWORD


services:
- name: mariadb:latest
  alias: testmysql_with_data
- name: mariadb:latest
  alias: testmysql_without_data
- name: postgres:latest
  alias: testpostgres_without_data

connect:
  image: mariadb:latest
  script:
  - echo "SELECT 'OK';" | mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=testmysql_with_data "$MYSQL_DATABASE"


before_script:
  - cat /etc/issue
  - bash docker/build-base.sh

build:
  stage: build
  script:
    - make init

test:
  stage: test
  script:
    - make test

