image: docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DB_PASSWORD: dbcuttest
  DB_NAME: dbcuttest
  DB_USER: dbcuttest


before_script:
  - docker version
  - docker-compose version

stages:
  - build
  - test

build:
  stage: build
  script:
    - docker-compose build

test:
  stage: test
  script:
    - docker-compose run --rm dbcut_app
