image:
  name: docker/compose:1.23.2
  entrypoint: [""]

stages:
  - build
  - test

build:
  stage: build
  script:
    - docker-compose build

test:
  stage: test
  script:
    - docker-compose run --rm dbcut_app
