version: '3.7'

x-default-service: &defaults
  restart: unless-stopped
  environment:
    MYSQL_HOST: mysql_test
    POSTGRES_HOST: postgres_test

    SQLITE_DB: dbcuttest.sqlite

    POSTGRES_PASSWORD: dbcuttest
    POSTGRES_DB: dbcuttest
    POSTGRES_DB_2: dbcuttest_2
    POSTGRES_USER: dbcuttest

    MYSQL_ROOT_PASSWORD: dbcuttest
    MYSQL_PASSWORD: dbcuttest
    MYSQL_DATABASE: dbcuttest
    MYSQL_DATABASE_2: dbcuttest_2
    MYSQL_USER: dbcuttest

services:

  dbcut_app:
    <<: *defaults
    container_name: dbcut_app_${CI_JOB_ID:-1}
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        PYTHON_IMAGE: ${PYTHON_IMAGE:-python:3.6}
    depends_on:
      - mysql_test
      - postgres_test
    volumes:
      - .:/app

  mysql_test:
    container_name: mysql_test_${CI_JOB_ID:-1}
    <<: *defaults
    image: ${MYSQL_IMAGE:-mariadb:10.3}
    volumes:
      - ./docker/mysql_test/:/docker-entrypoint-initdb.d:ro

  postgres_test:
    container_name: mysql_test_${CI_JOB_ID:-1}
    <<: *defaults
    image: ${POSTGRES_IMAGE:-postgres:9.5}
