[pytest]
norecursedirs=.git .tox venv env
addopts=--doctest-modules --tb native -r fxX --maxfail=25 --ignore=setup.py --ignore=scripts
doctest_optionflags= NORMALIZE_WHITESPACE IGNORE_EXCEPTION_DETAIL ALLOW_UNICODE
